# Generated by Django 5.2.4 on 2025-07-22 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('nickname', models.TextField()),
                ('gender', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.TextField()),
                ('address', models.TextField()),
                ('joinDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidultMallApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.BigAutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=30)),
                ('shippingAddress', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidultMallApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kidultMallApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidultMallApp.product')),
            ],
        ),
    ]
