# Generated by Django 5.2.4 on 2025-07-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidultMallApp', '0002_alter_board_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='showCount',
            field=models.IntegerField(default=0),
        ),
    ]
