# Generated by Django 5.2.4 on 2025-07-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidultMallApp', '0003_board_showcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
        migrations.AddField(
            model_name='board',
            name='no',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
