# Generated by Django 5.2.4 on 2025-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidultMallApp', '0004_remove_board_id_board_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
