# Generated by Django 5.2.4 on 2025-07-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidultMallApp', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartOwner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kidultMallApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidultMallApp.cart')),
                ('productInCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidultMallApp.product')),
            ],
        ),
    ]
